# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Abusing and Protecting Kubernetes, Linux and Containers"
email: contact@inguardians.com
description: >- # this means to ignore newlines until "baseurl:"

Learn how to attack and defend Kubernetes, Linux and containers from Jay Beale, the creator of Bastille Linux and two Kubernetes security tools: the Peirates attack tool and the Bust-a-Kube CTF cluster. In this fully hands-on course, you'll get a laptop to keep, filled with capture-the-flag (CTF) machines, Kubernetes clusters, and containers, which you will attack and defend. You’ll also get access to our cloud environment, allowing you to attack cloud-based Kubernetes clusters.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: inguardians
github_username:  inguardians
slack_url: https://example.slack.com/

# Build settings
markdown: CommonMarkGhPages
theme: minima
plugins:
  - jekyll-feed

permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
